# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            selketjah
tagline:          'Blog mostly about books and sometimes about programming'
description:      'Understanding problems, one system at a time'
url:              https://selketjah.github.io/
baseurl:          https://selketjah.github.io/

author:
  name:           'Gien Verschatse'
  url:            https://twitter.com/selketjah

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/selketjah/selketjah.github.io
