# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            selketjah
tagline:          'Blog about books and sometimes about programming'
description:      ''
url:              https://selketjah.github.io/
baseurl:          https://selketjah.github.io/

author:
  name:           'Gien Verschatse'
  url:            https://twitter.com/selketjah

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/selketjah/selketjah.github.io
